# Generated by Django 4.2 on 2023-04-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cathegory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cats',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.cathegory'),
        ),
    ]
